### ISSUE TITLE
Timer doesn't stop when using in tests

### ISSUE THREAD

**Issue by eden-lane** [LobsterBandit/use-countdown-timer#26]
Here is my component's code:

```
const Component = ({onSend}) => {
  const { countdown, start, reset, isRunning } = useCountdownTimer({
    timer: 1000 * 30,
  });

  const handleSubmit = useCallback(
    (values) => {
      onSend(values.phone);
      reset();
      start();
    },
    [start, reset, onSend];
  );
  
  return (
    <Button onClick={handleSubmit} disabled={isRunning}>Submit {countdown / 1000}</Button>
  );
}
```

and here is my test:
```
expect(submitButton).toBeDisabled();

act(() => {
  jest.advanceTimersByTime(31000);
});

expect(submitButton).toBeEnabled();
```

I found out that timer doesn't stop in this case, it shows 0 seconds, then -1 second, -2 seconds and so on...

Am I doing something wrong?

**Comment by LobsterBandit** [comment]
From a basic create-react-app template, works for me with this component:
```js
import { useCallback, useState } from "react";
import { useCountdownTimer } from "use-countdown-timer";

function App() {
  const { countdown, start, reset, isRunning } = useCountdownTimer({
    timer: 1000 * 30,
  });
  const [phone, setPhone] = useState("");

  const handleSubmit = useCallback(
    (phone) => {
      console.log(phone);
      reset();
      start();
    },
    [start, reset]
  );

  return (
    <div>
      <label htmlFor="phone-input">Phone</label>
      <input
        type="text"
        value={phone}
        onChange={(e) => setPhone(e.target.value)}
        id="phone-input"
      />
      <button
        disabled={isRunning}
        onClick={() => handleSubmit(phone)}
      >{`Submit ${countdown / 1000}`}</button>
    </div>
  );
}

export default App;
```

And this test:
```js
import { act, fireEvent, render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import App from "./App";

test("Submit button works", () => {
  jest.useFakeTimers();

  render(<App />);

  const submitButton = screen.getByText(/Submit/);

  userEvent.type(screen.getByLabelText("Phone"), "123");
  fireEvent.click(submitButton);

  expect(submitButton).toBeDisabled();

  act(() => {
    jest.advanceTimersByTime(31000);
  });

  console.log(submitButton.innerHTML);

  expect(submitButton).toBeEnabled();
});
```

```sh
PASS  src/App.test.js
  ✓ Submit button works (207 ms)

  console.log
    123

      at handleSubmit (src/App.js:13:15)

  console.log
    Submit 30

      at Object.<anonymous> (src/App.test.js:21:11)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        2.237 s
Ran all test suites related to changed files.

Watch Usage: Press w to show more.
```
